#!/bin/bash
#SBATCH --job-name=btk_view # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com     # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=10	# Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=00-00:10:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/NES739_purge_haplotigs/NES739_Blob

module load anaconda3

conda activate btk

export PATH=/path/to/BlobToolKit:$PATH

blobtools view \
    --out ./NES739_Blob \
    --format svg \
    --format png \
    --view blob \
    --view snail \
    --plot \
    NES739_Blob

    ##commands also executable via terminal
