#!/bin/bash
#SBATCH --job-name=btk_summary_table # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com    # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=10            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=00-00:10:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/NES739_purge_haplotigs/NES739_Blob/polished_assembly_fasta/filtered_no_hit

module load anaconda3
module load R/4.5.1
source ~/.bashrc
conda activate btk

##### Before filtering #####

#blobtools filter \
#	--table NES739_Blob/NES739_summary_table.tsv \
#	NES739_Blob

#R CMD BATCH --no-save write_blobtools_summary_table.R


##### After filtering #####

blobtools filter \
	--table NES739_filtered_summary_table.tsv \
	.

R CMD BATCH --no-save get_keep_list_from_blobtools_table_739.R
