#!/bin/bash
#SBATCH --job-name=bam2fastq
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ypur@email.com
#SBATCH --nodes=1-1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=48gb
#SBATCH --time=00-06:00:00
#SBATCH --output=bam2fastq_%j.log
#SBATCH --chdir=/path/to/raw/fastq.gz

module load anaconda3
source $(conda info --base)/etc/profile.d/conda.sh
conda activate /scratch/jr4253/miniconda3/envs/assembly

# Create a new file and generate a header line
#echo "platform,length" > length.csv
# Add each read length into the length.csv file.
#bioawk -c fastx ’{print "PacBio_CLR," length($seq)}’ SRR11906525_WGS_of_drosophila_melanogaster_
#female_adult_subreads.fastq.gz >> length.csv
#bioawk -c fastx '{print "PacBio_HiFi," length($seq)}' NES739.hifi_reads.fastq.gz
#bioawk -c fastx ’{print "ONT," length($seq)}’ SRR13070625_1.fastq.gz >> length.csv

# Create a new file and generate a header line
echo "platform,length" > length.csv

# Add each read length into the length.csv file
bioawk -c fastx '{print "PacBio_HiFi," length($seq)}' NES739.hifi_reads.fastq.gz >> length.csv
