#!/bin/bash
#SBATCH --job-name=sam2bam # Job name
#SBATCH --mail-type=BEGIN,END, FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com     # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=10            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=01-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=sam_2_bam_%j.log     # Standard output and error log
#SBATCH --chdir=/scratch/jr4253/NES739_assembly/NES739_Referee

module load samtools/1.15.1

samtools view -b NES739_reads_mapped_hd.sam > NES739_reads_mapped_hd.bam
