#!/bin/bash
#SBATCH --job-name=angsd # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com    # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=10            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=04-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=angsd_%j.log     # Standard output and error log
#SBATCH --chdir=/scratch/jr4253/NES739_assembly/NES739_Referee

set -euo pipefail

export MAMBA_ROOT_PREFIX=/scratch/jr4253/micromamba
eval "$(/scratch/jr4253/bin/micromamba shell hook --shell bash)"
micromamba activate referee


angsd -GL 2 -i NES739_reads_mapped_hd_sorted.bam -ref NES739_hifi_filtered_no_hit.fasta -minQ 0 -doGlf 4 -nThreads 10 -o reads_gl
