#!/bin/bash
#SBATCH --job-name=Ref_angsd # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com     # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=10            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=02-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=referee_angsd_%j.log     # Standard output and error log
#SBATCH --chdir=/scratch/jr4253/NES739_assembly/NES739_Referee

set -euo pipefail

export MAMBA_ROOT_PREFIX=/scratch/jr4253/micromamba
eval "$(/scratch/jr4253/bin/micromamba shell hook --shell bash)"
micromamba activate referee


python /scratch/jr4253/software/referee/referee.py -gl reads_gl.glf.gz -ref NES739_hifi_filtered_no_hit.fasta --fastq –bed --correct -p 10 -d NES739_referee


##specify –bed to view in a genome viewer!!
