#!/bin/bash
#SBATCH --job-name=mapping_sorting # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com    # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=16            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=01-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/your/files

source ~/.bashrc

conda activate minimap
module load samtools/1.15.1

minimap2 -t 16 -ax map-hifi \
  NES739.bp.p_ctg.fa \
  NES739.hifi_reads.filt.fastq.gz \
  --secondary=no \
| samtools sort -@ 8 -o NES739.bp.p_ctg.sorted.bam
