#!/bin/bash
#SBATCH --job-name=generate_histogram # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com    # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=10            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=00-01:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/your/files

module load anaconda3

conda activate purge_haplotigs

purge_haplotigs hist \
  -b NES739.bp.p_ctg.sorted.bam \
  -g NES739.bp.p_ctg.fa

conda deactivate

# Optional; it's required only if haplotigs are present
