#!/bin/bash
#SBATCH --job-name=jelly_kmer
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=your@email.com
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5
#SBATCH --mem=10gb
#SBATCH --time=12:00:00
#SBATCH --output=jelly_kmer_%j.log
#SBATCH --chdir=/path/to/raw/fastq

module load anaconda3
module load openmpi
conda activate jellyfish

# Step 1: Count k-mers (canonical)
jellyfish count -C -m 21 -s 10G -t 5 NES739.hifi_reads.fastq -o NES739.hifi_reads.jf

# Step 2: Generate histogram
jellyfish histo -t 5 NES739.hifi_reads.jf > NES739.hifi_reads.histo


conda deactivate
