#!/bin/bash
#SBATCH --job-name=repeatmasker_1st # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email     # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32	# Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=01-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/polished_assembly_fasta

source ~/.bashrc
micromamba activate repeatmodeler


out_dir="NES739_repeatmasker"
mkdir -p "$out_dir"

input_fasta="NES739_purge_haplotigs/NES739_Blob/polished_assembly_fasta/filtered_no_hit/NES739_hifi_filtered_no_hit.fasta"

RepeatMasker \
    -species metazoa \
    -s \
    -pa 10 \
    -xsmall \
    -alignments \
    -dir "$out_dir" \
    "$input_fasta"
