#!/bin/bash
#SBATCH --job-name=prothint # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com    # Where to send mail
#SBATCH --nodes=1-1                   # Run a single task
#SBATCH --ntasks-per-node=32            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=00-03:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=parallel_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/polished/assembly

#cat Carabus_problematicus_protein.fa Nebria_brevicollis_protein.fa Pterostichus_madidus_protein.fa > conca_proteins.fasta

# Load Perl modules installed in your home directory
export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB
export PATH=$HOME/perl5/bin:$PATH

export ProtHint_DIR=/scratch/jr4253/GeneMark-ETP/bin/gmes/ProtHint/bin
export PATH=$PATH:/scratch/jr4253/GeneMark-ETP/bin/gmes

$ProtHint_DIR/prothint.py \
	--threads 32 \
	NES739_hifi_filtered_no_hit.fasta.masked.masked \
	conca_proteins.fasta
