#!/bin/bash
#SBATCH --job-name=BUSCO      # Job name
#SBATCH --mail-type=BEGIN,END,FAIL         # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=your@email.com  # Where to send mail
#SBATCH --ntasks=1                   # Run a single task
#SBATCH --cpus-per-task=8            # Number of CPU cores per task
#SBATCH --mem=80gb            # Job memory request
#SBATCH --time=03-00:00:00              # Time limit days-hrs:min:sec
#SBATCH --output=BUSCO_%j.log     # Standard output and error log
#SBATCH --chdir=/path/to/braker/results

 
module load anaconda3
source /scratch/jr4253/miniconda3/etc/profile.d/conda.sh
conda activate busco6
export _JAVA_OPTIONS="-Xmx70g"

assembly="braker.aa"
outdir="NES739_carabid_results"

busco \
  -i "$assembly" \
  -o "$outdir" \
  -m protein \
  -l coleoptera_odb12 \
  -c 8 \
  -f
  
conda deactivate
